apiVersion: apps/v1
kind: Deployment
metadata:
  name: content-api
  labels:
    app: content-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: content-api
  template:
    metadata:
      labels:
        app: content-api
    spec:
      containers:
      - name: content-api
        image: whatthehackmsft/content-api:v2
        resources:
          requests:
            cpu: 500m
            memory: 128Mi
        ports:
        - containerPort: 3001
        env:
        - name: MONGODB_CONNECTION
          value: "mongodb://mongodb:27017/contentdb"


